### ISSUE TITLE
Re: KorkBoard LLC

### ISSUE THREAD

**Issue by vsitaraman** [jsedlak/Korkboard#1]
Hello John,
Please check your email at focusedgames.com for correspondence on behalf of KorkBoard LLC regarding this Github repo. Thank you.

**Comment by jsedlak** [comment]
That is not my email and hasn't been for a long time. Please email me at kriscsc@msn.com or post here. Thanks!

**Comment by vsitaraman** [comment]
Sounds good thanks!

**Comment by vsitaraman** [comment]
Sounds good! Just dropped you an e-mail there.

**Comment by vsitaraman** [comment]
John, just checking if you received my message to your e-mail on behalf of Korkboard LLC. Thanks!

**Comment by vsitaraman** [comment]
John, thanks for changing the name! Can you also change the name of the solution and folder under "source." Thanks!
